name: Java CI/CD with Maven and Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: testdb
        ports:
          - "5432:5432"
        options: >-
          --health-cmd="pg_isready -U test -d testdb"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20

    env:
      SPRING_PROFILES_ACTIVE: ci
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/testdb
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test
      CLIENT_ID: ${{ secrets.CLI_ID }}
      CLIENT_SECRET: ${{ secrets.CLI_SEC }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install psql client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Seed database from SEED_SQL_B64 (bash guard)
        env:
          PGPASSWORD: test
          SEED_SQL_B64: ${{ secrets.SEED_SQL_B64 }}
        run: |
          if [ -z "${SEED_SQL_B64}" ]; then
            echo "SEED_SQL_B64 is empty. Skipping seed import."
            exit 0
          fi

          echo "$SEED_SQL_B64" | base64 -d > seed.sql

          # Strip PG17-only and pgAdmin junk your app doesn't need
          sed -i -E \
            -e '/^SET[[:space:]]+transaction_timeout[[:space:]]*=/d' \
            -e "/SELECT pg_catalog\.set_config\('transaction_timeout',/d" \
            -e '/^CREATE EXTENSION[[:space:]]+adminpack/d' \
            -e '/^COMMENT ON EXTENSION[[:space:]]+adminpack/d' \
            -e '/^ALTER EXTENSION[[:space:]]+adminpack/d' \
            seed.sql

          # Wait for DB to be ready
          for i in {1..30}; do
            pg_isready -h localhost -p 5432 -U test -d testdb && break || sleep 2
          done

          # Import and fail fast on SQL errors
          psql -h localhost -p 5432 -U test -d testdb -v ON_ERROR_STOP=1 -f seed.sql
      

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build and Test
        run: mvn -B -Dspring.profiles.active=ci test
